version: "2.2"
services:
  live-origin:
    image: unifiedstreaming/live:1.10.18
    ports:
      - 80:80
    environment:
      - USP_LICENSE_KEY
      - CHANNEL=cmaf-ingest
      - PUB_POINT_OPTS=--timed_metadata --splice_media --archiving=1 --archive_length=1200 --archive_segment_length=300 --dvr_window_length=600 --restart_on_encoder_reconnect --hls.client_manifest_version=4 --hls.no_multiplex
    healthcheck:
      test: kill -0 1
      interval: 2s
      timeout: 5s
      retries: 30
  cmaf-ingest-image:
    build: ./cmaf-ingest-image
    environment:
       - PUB_POINT_URI=http://live-origin/cmaf-ingest/cmaf-ingest.isml
       - CMAF_FILES=tos-096-750k.cmfv tos-096s-128k.cmfa tos-de-096s.cmft tos-en-096s.cmft tos-es-096s.cmft tos-fr-096s.cmft
       - CMD_ARGS=-r -l 10000 --wc_offset --avail 57600 9600
       - LOGO_OVERLAY=
    depends_on:
      live-origin:
        condition: service_healthy
